"use client";

import { useState } from "react";
import { Crown, History, Shield, Swords, Trophy } from "lucide-react";
import data from "@/app/data/core_history.json";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

type Standing = (typeof data.manager_history.standings)[number];
type Season = (typeof data.seasons)[number];
type RecordEntry = { season:number; matchup_period?:number; scoring_period?:number; team_name?:string; manager_names?:string[]; points?:number; home_team_name?:string; home_manager_names?:string[]; home_score?:number; away_team_name?:string; away_manager_names?:string[]; away_score?:number; margin?:number; combined_score?:number };
const fmt = new Intl.NumberFormat("en-US", { maximumFractionDigits: 2 });
const names = (x?: string[]) => x?.join(" & ") ?? "—";

function Standings({ rows }: { rows: Standing[] }) {
  return <div className="table-shell"><Table><TableHeader><TableRow><TableHead>#</TableHead><TableHead>Current team</TableHead><TableHead>Seasons</TableHead><TableHead>Record</TableHead><TableHead>Win %</TableHead><TableHead>Points</TableHead><TableHead>Playoffs</TableHead><TableHead>Finals</TableHead><TableHead>Titles</TableHead></TableRow></TableHeader><TableBody>
    {rows.map((m,i)=>{const currentTeam=[...m.team_names].sort((a,b)=>b.season-a.season)[0]?.team_name??"—";return <TableRow key={m.manager_id}><TableCell className="rank">{i+1}</TableCell><TableCell><strong>{currentTeam}</strong><small>{m.manager_name}</small></TableCell><TableCell>{m.seasons}</TableCell><TableCell>{m.wins}–{m.losses}</TableCell><TableCell><strong>{((m.winning_percentage??0)*100).toFixed(1)}%</strong></TableCell><TableCell>{fmt.format(m.points_for)}</TableCell><TableCell>{m.playoff_appearances}</TableCell><TableCell>{m.runner_up_finishes+m.championships}</TableCell><TableCell className="titles">{m.championships||"—"}</TableCell></TableRow>})}
  </TableBody></Table></div>;
}

function RecordCard({ label, title, record, value }: {label:string;title:string;record:RecordEntry;value:string}) {
  return <article className="record-card"><p className="eyebrow">{label}</p><div className="record-value">{value}</div><h3>{title}</h3><p>{record.points!==undefined?names(record.manager_names):`${names(record.home_manager_names)} vs. ${names(record.away_manager_names)}`}</p><small>{record.season} · Week {record.scoring_period??record.matchup_period}</small></article>;
}

function SeasonArchive({ season }: {season:Season}) {
  const [week,setWeek]=useState("1");
  const teams=[...season.teams].sort((a,b)=>(a.playoff_seed??99)-(b.playoff_seed??99));
  const champ=season.teams.find(t=>t.final_rank===1); const runner=season.teams.find(t=>t.final_rank===2);
  const periods=[...new Set(season.weekly_scores.filter(s=>s.opponent_team_id!==null).map(s=>s.scoring_period))].sort((a,b)=>a-b);
  const selected=Number(week); const scoreRows=season.weekly_scores.filter(s=>s.scoring_period===selected&&s.opponent_team_id!==null);
  const scoreMap=new Map(scoreRows.map(s=>[s.team_id,s]));
  const games=scoreRows.filter(s=>s.team_id<(s.opponent_team_id??0)).map(s=>({a:s,b:scoreMap.get(s.opponent_team_id!)})).filter(g=>g.b);
  return <><div className="season-grid"><aside className="season-card"><span className="watermark">{season.season}</span><Trophy/><p className="eyebrow">League champion</p><h3>{names(champ?.manager_names)}</h3><p>{champ?.team_name}</p><dl><div><dt>Regular-season record</dt><dd>{champ?.regular_season.wins}–{champ?.regular_season.losses}</dd></div><div><dt>Regular-season seed</dt><dd>#{champ?.playoff_seed}</dd></div><div><dt>Runner-up</dt><dd>{names(runner?.manager_names)}</dd></div></dl></aside>
  <div><p className="eyebrow">Regular-season standings</p><div className="table-shell no-top"><Table><TableHeader><TableRow><TableHead>Seed</TableHead><TableHead>Manager</TableHead><TableHead>Team</TableHead><TableHead>Record</TableHead><TableHead>PF</TableHead><TableHead>PA</TableHead><TableHead>Final finish</TableHead></TableRow></TableHeader><TableBody>{teams.map(t=><TableRow key={t.team_season_id}><TableCell className="rank">#{t.playoff_seed}</TableCell><TableCell><strong>{names(t.manager_names)}</strong></TableCell><TableCell>{t.team_name}</TableCell><TableCell>{t.regular_season.wins}–{t.regular_season.losses}</TableCell><TableCell>{fmt.format(t.regular_season.points_for)}</TableCell><TableCell>{fmt.format(t.regular_season.points_against)}</TableCell><TableCell>{t.final_rank===1?"Champion":t.final_rank===2?"Runner-up":`#${t.final_rank}`}</TableCell></TableRow>)}</TableBody></Table></div></div></div>
  <PlayoffBracket season={season}/>
  <section className="weekly-results"><div className="section-title compact"><div><p className="eyebrow">Full scoreboard</p><h2>Weekly results</h2></div><Select value={week} onValueChange={setWeek}><SelectTrigger aria-label="Select scoring week"><SelectValue/></SelectTrigger><SelectContent>{periods.map(p=><SelectItem key={p} value={String(p)}>Week {p}</SelectItem>)}</SelectContent></Select></div><div className="score-grid">{games.map(({a,b})=><article key={`${selected}:${a.matchup_id}:${a.team_id}`}><div className={(a.points>(b?.points??0)?"winner ":"")+"score-side"}><span><b>{a.team_name}</b><small>{names(a.manager_names)}</small></span><strong>{fmt.format(a.points)}</strong></div><div className={((b?.points??0)>a.points?"winner ":"")+"score-side"}><span><b>{b?.team_name}</b><small>{names(b?.manager_names)}</small></span><strong>{fmt.format(b?.points??0)}</strong></div></article>)}</div></section></>;
}

function PlayoffBracket({season}:{season:Season}) {
  const rounds=season.matchups.filter(m=>m.stage==="championship_playoffs"&&m.home_team_id!==null&&m.away_team_id!==null);
  const labels:Record<number,string>={1:"Quarterfinals",2:"Semifinals",3:"Championship"};
  return <section className="bracket-wrap"><div className="section-title compact"><div><p className="eyebrow">Championship playoffs</p><h2>Playoff bracket</h2></div><p>Final series totals are combined across both championship weeks.</p></div><div className="bracket">{[1,2,3].map(round=><div className="bracket-round" key={round}><h3>{labels[round]}</h3>{rounds.filter(m=>m.playoff_round===round).map(m=><article key={m.matchup_key}><div className={m.winner==="HOME"?"winner":""}><span><b>{m.home_team_name}</b><small>{names(m.home_manager_names)}</small></span><strong>{fmt.format(m.home_score??0)}</strong></div><div className={m.winner==="AWAY"?"winner":""}><span><b>{m.away_team_name}</b><small>{names(m.away_manager_names)}</small></span><strong>{fmt.format(m.away_score??0)}</strong></div>{m.is_multiweek_series&&<small>Two-week total</small>}</article>)}</div>)}</div></section>;
}

function CurrentSeason({ season }: {season?:Season}) {
  if(!season) return <section className="empty-live"><p className="eyebrow gold">2026 Live</p><h2>Current-season data is ready to be pulled.</h2><p>Run the 2026 ESPN discovery and rebuild the history to activate this page.</p></section>;
  const standings=[...season.teams].sort((a,b)=>(a.playoff_seed??99)-(b.playoff_seed??99));
  const complete=season.matchups.filter(m=>m.stage==="regular_season"&&m.decided&&m.home_team_id!==null&&m.away_team_id!==null);
  const completedIds=new Set(complete.map(m=>m.matchup_id));
  const scores=season.weekly_scores.filter(s=>completedIds.has(s.matchup_id));
  const weeklyHigh=scores.length?[...scores].sort((a,b)=>b.points-a.points)[0]:undefined;
  const latestGames=complete.filter(m=>m.matchup_period===season.through_week);
  const pointsLeader=[...season.teams].sort((a,b)=>b.regular_season.points_for-a.regular_season.points_for)[0];
  return <><section className="live-banner"><div><p className="eyebrow">Current season</p><h2>{season.season} Live</h2><p>{season.through_week?`Standings and official results through Week ${season.through_week}.`:"Standings are live; Week 1 results are not final yet."}</p></div><span className="live-pill"><i/>In progress</span></section>
  <section className="live-cards"><article><p className="eyebrow">Current leader</p><strong>{names(standings[0]?.manager_names)}</strong><span>{standings[0]?.regular_season.wins}–{standings[0]?.regular_season.losses} · {standings[0]?.team_name}</span></article><article><p className="eyebrow">Points leader</p><strong>{names(pointsLeader?.manager_names)}</strong><span>{fmt.format(pointsLeader?.regular_season.points_for??0)} points</span></article><article><p className="eyebrow">Season high</p><strong>{weeklyHigh?fmt.format(weeklyHigh.points):"—"}</strong><span>{weeklyHigh?`${names(weeklyHigh.manager_names)} · Week ${weeklyHigh.scoring_period}`:"No completed games"}</span></article></section>
  <div className="section-title compact"><div><p className="eyebrow">Playoff picture</p><h2>Current standings</h2></div><p>Seeds reflect ESPN&apos;s current league order.</p></div><div className="table-shell"><Table><TableHeader><TableRow><TableHead>Seed</TableHead><TableHead>Manager</TableHead><TableHead>Team</TableHead><TableHead>Record</TableHead><TableHead>PF</TableHead><TableHead>PA</TableHead></TableRow></TableHeader><TableBody>{standings.map(t=><TableRow key={t.team_season_id}><TableCell className="rank">#{t.playoff_seed}</TableCell><TableCell><strong>{names(t.manager_names)}</strong></TableCell><TableCell>{t.team_name}</TableCell><TableCell>{t.regular_season.wins}–{t.regular_season.losses}</TableCell><TableCell>{fmt.format(t.regular_season.points_for)}</TableCell><TableCell>{fmt.format(t.regular_season.points_against)}</TableCell></TableRow>)}</TableBody></Table></div>
  {season.through_week>0&&<><div className="section-title compact"><div><p className="eyebrow">Latest completed week</p><h2>Week {season.through_week} results</h2></div></div><section className="score-grid">{latestGames.map(g=><article key={g.matchup_key}><div className={(g.winner==="HOME"?"winner ":"")+"score-side"}><span>{names(g.home_manager_names)}</span><strong>{fmt.format(g.home_score??0)}</strong></div><div className={(g.winner==="AWAY"?"winner ":"")+"score-side"}><span>{names(g.away_manager_names)}</span><strong>{fmt.format(g.away_score??0)}</strong></div></article>)}</section></>}</>;
}

export default function Home() {
  const [year,setYear]=useState(2025); const season=data.seasons.find(s=>s.season===year)??data.seasons[0];
  const regular=data.records.regular_season, playoffs=data.records.championship_playoffs, series=data.records.multiweek_playoff_series;
  const latestSeason=[...data.seasons].reverse().find(s=>s.is_complete)!;
  const latestChampion=latestSeason.teams.find(t=>t.final_rank===1)!;
  const currentSeason=data.seasons.find(s=>!s.is_complete);
  return <main><header className="site-header"><div className="crest"><b>CGL</b><small>EST. 2024</small></div><div><p>Charley&apos;s Gonna Lose</p><h1>Official Record Book</h1></div><div className="seal"><Shield/><span>League<br/>History</span></div></header>
  <Tabs defaultValue="overview" className="tabs"><nav><TabsList variant="line"><TabsTrigger value="overview">Overview</TabsTrigger><TabsTrigger value="current">2026 Live</TabsTrigger><TabsTrigger value="champions">Champions</TabsTrigger><TabsTrigger value="standings">Standings</TabsTrigger><TabsTrigger value="records">Records</TabsTrigger><TabsTrigger value="seasons">Seasons</TabsTrigger></TabsList></nav>
  <TabsContent value="overview" className="page"><section className="lede"><div><p className="eyebrow gold">The books are open</p><h2>{data.records.counts.seasons} seasons.<br/><em>One official history.</em></h2><p className="intro">Every matchup, title and heartbreak since CGL&apos;s official record era began in 2024.</p><p className="legend"><History/> Pre-2024 championships live on as league legend.</p></div><article className="reigning"><Crown/><p className="eyebrow">Reigning champion · {latestSeason.season}</p><h3>{names(latestChampion.manager_names)}</h3><p>{latestChampion.team_name}</p><div><span><b>{latestChampion.regular_season.wins}–{latestChampion.regular_season.losses}</b>Regular season</span><span><b>#{latestChampion.playoff_seed}</b>Playoff seed</span></div></article></section>
  <section className="totals"><div><b>{data.records.counts.seasons}</b><span>Seasons</span></div><div><b>{data.records.counts.regular_season_matchups}</b><span>Regular-season games</span></div><div><b>{data.managers.length}</b><span>Managers</span></div><div><b>{data.records.champions.length}</b><span>Champions</span></div></section>
  <div className="section-title"><div><p className="eyebrow">All-time pace setters</p><h2>Winning percentage</h2></div><p>Career regular-season records. No minimum games—yet.</p></div><Standings rows={data.manager_history.standings.slice(0,5)}/>
  <section className="record-grid spaced"><RecordCard label="Single-week high" title={regular.highest_weekly_score.team_name} record={regular.highest_weekly_score} value={fmt.format(regular.highest_weekly_score.points)}/><RecordCard label="Closest finish" title={`${regular.closest_game.home_team_name} / ${regular.closest_game.away_team_name}`} record={regular.closest_game} value={`${fmt.format(regular.closest_game.margin)} pts`}/><RecordCard label="Largest rout" title={`${regular.largest_margin.home_team_name} / ${regular.largest_margin.away_team_name}`} record={regular.largest_margin} value={`${fmt.format(regular.largest_margin.margin)} pts`}/></section></TabsContent>

  <TabsContent value="current" className="page"><CurrentSeason season={currentSeason}/></TabsContent>

  <TabsContent value="champions" className="page"><PageHead overline="The highest honor" title="Championship ledger" text="Official CGL champions beginning with the 2024 season."/><div className="ledger">{data.records.champions.map(c=>{const s=data.seasons.find(x=>x.season===c.season)!;const t=s.teams.find(x=>x.team_id===c.team_id)!;const ru=s.teams.find(x=>x.final_rank===2)!;const f=s.matchups.find(x=>x.stage==="championship_playoffs"&&x.is_multiweek_series&&(x.home_team_id===c.team_id||x.away_team_id===c.team_id));return <article key={c.season}><strong className="year">{c.season}</strong><span className="medal"><Trophy/></span><div><p className="eyebrow">CGL champion</p><h3>{names(c.manager_names)}</h3><p>{c.team_name}</p></div><dl><div><dt>Regular season</dt><dd>{t.regular_season.wins}–{t.regular_season.losses} · #{t.playoff_seed} seed</dd></div><div><dt>Championship</dt><dd>{f?`${fmt.format(Math.max(f.home_score??0,f.away_score??0))}–${fmt.format(Math.min(f.home_score??0,f.away_score??0))}`:"—"} vs. {names(ru.manager_names)}</dd></div></dl></article>})}</div></TabsContent>

  <TabsContent value="standings" className="page"><PageHead overline="Every season counts" title="All-time standings" text="Ranked by regular-season winning percentage, then wins and points scored."/><Standings rows={data.manager_history.standings}/></TabsContent>

  <TabsContent value="records" className="page"><PageHead overline="Best, worst & wildest" title="The record board" text="Consolation games are preserved in season history but excluded here."/>
  <RecordGroup number="01" name="Regular season"><RecordCard label="Highest score" title={regular.highest_weekly_score.team_name} record={regular.highest_weekly_score} value={fmt.format(regular.highest_weekly_score.points)}/><RecordCard label="Lowest score" title={regular.lowest_weekly_score.team_name} record={regular.lowest_weekly_score} value={fmt.format(regular.lowest_weekly_score.points)}/><RecordCard label="Highest score in a loss" title={regular.highest_score_in_loss.team_name} record={regular.highest_score_in_loss} value={fmt.format(regular.highest_score_in_loss.points)}/><RecordCard label="Lowest score in a win" title={regular.lowest_score_in_win.team_name} record={regular.lowest_score_in_win} value={fmt.format(regular.lowest_score_in_win.points)}/><RecordCard label="Largest margin" title={`${regular.largest_margin.home_team_name} / ${regular.largest_margin.away_team_name}`} record={regular.largest_margin} value={fmt.format(regular.largest_margin.margin)}/><RecordCard label="Closest game" title={`${regular.closest_game.home_team_name} / ${regular.closest_game.away_team_name}`} record={regular.closest_game} value={fmt.format(regular.closest_game.margin)}/></RecordGroup>
  <RecordGroup number="02" name="Championship playoffs"><RecordCard label="Highest playoff week" title={playoffs.highest_weekly_score.team_name} record={playoffs.highest_weekly_score} value={fmt.format(playoffs.highest_weekly_score.points)}/><RecordCard label="Lowest playoff week" title={playoffs.lowest_weekly_score.team_name} record={playoffs.lowest_weekly_score} value={fmt.format(playoffs.lowest_weekly_score.points)}/><RecordCard label="Largest playoff margin" title={`${playoffs.largest_single_week_or_round_margin.home_team_name} / ${playoffs.largest_single_week_or_round_margin.away_team_name}`} record={playoffs.largest_single_week_or_round_margin} value={fmt.format(playoffs.largest_single_week_or_round_margin.margin)}/></RecordGroup>
  <RecordGroup number="03" name="Two-week championship series"><RecordCard label="Largest series margin" title={`${series.largest_margin.home_team_name} / ${series.largest_margin.away_team_name}`} record={series.largest_margin} value={fmt.format(series.largest_margin.margin)}/><RecordCard label="Closest series" title={`${series.closest_series.home_team_name} / ${series.closest_series.away_team_name}`} record={series.closest_series} value={fmt.format(series.closest_series.margin)}/><RecordCard label="Highest combined" title={`${series.highest_combined_score.home_team_name} / ${series.highest_combined_score.away_team_name}`} record={series.highest_combined_score} value={fmt.format(series.highest_combined_score.combined_score)}/></RecordGroup></TabsContent>

  <TabsContent value="seasons" className="page"><div className="season-head"><PageHead overline="Year by year" title="Season archive"/><div className="year-pick">{data.seasons.filter(s=>s.is_complete).map(s=><button key={s.season} className={s.season===year?"active":""} onClick={()=>setYear(s.season)}>{s.season}</button>)}</div></div><SeasonArchive key={season.season} season={season}/></TabsContent></Tabs>
  <footer><div className="crest mini"><b>CGL</b></div><p>Official statistical history begins in 2024.</p><Swords/></footer></main>;
}

function PageHead({overline,title,text}:{overline:string;title:string;text?:string}) { return <header className="page-head"><p className="eyebrow gold">{overline}</p><h2>{title}</h2>{text&&<p>{text}</p>}</header>; }
function RecordGroup({number,name,children}:{number:string;name:string;children:React.ReactNode}) { return <section className="record-group"><div><strong>{number}</strong><p className="eyebrow">Record class</p><h3>{name}</h3></div><div className="record-grid">{children}</div></section>; }
